# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Lyrics' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Firestore'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport',
    'RCTText',
    'RCTNetwork',
    'RCTImage',
    'RCTWebSocket',
  ]
  pod 'BVLinearGradient', :path => '../node_modules/react-native-linear-gradient'
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'

  pod 'RNSVG', :path => '../node_modules/react-native-svg'

  target 'LyricsTests' do
    inherit! :search_paths
    # Pods for testing
  end

end


#target 'Lyrics-tvOS' do
#  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
#  # use_frameworks!
#
#  # Pods for Lyrics-tvOS
#
#  target 'Lyrics-tvOSTests' do
#    inherit! :search_paths
#    # Pods for testing
#  end
#
#end
